#!/usr/bin/env bash
# setup-serial-udev.sh — install the bench serial ROLE ALIASES (2026-07-23).
#
# Rationale: raw ttyACMx names renumber on every replug/reflash and have burned
# us three times (by-id literal: bootloader renames; ttyACM* glob: matched the
# debug adapter; camera FTDI probed by a stray DFU touch). Tooling references
# ONLY these aliases: /dev/rak-cdc (flash + CDC log) and /dev/rak-debug
# (hardware tap on WB_IO1, survives reflashes).
#
# Idempotent: re-running REPLACES the previous rules file wholesale.
set -euo pipefail

# ---- mapping (edit here) -----------------------------------------------------
# One entry per alias: "name|usb_vid|usb_serial"  (usb_serial empty = match any
# device with that VID — used for the RAK because its VID 239a is the same in
# app AND bootloader mode, which is what keeps the alias alive mid-flash).
MAPPINGS=(
  "rak-cdc|239a|"                 # RAK4631 native USB (app + bootloader)
  "rak-debug|1a86|5B1F007437"     # WCH USB-serial adapter on the WB_IO1 debug tap
)
RULES_FILE=/etc/udev/rules.d/99-pac-serial.rules
# -------------------------------------------------------------------------------

if [[ $EUID -ne 0 ]]; then
  echo "must run as root (writes $RULES_FILE)" >&2
  exit 1
fi

{
  echo "# GENERATED by mt-transport/tools/setup-serial-udev.sh — edit THERE, re-run to replace."
  echo "# $(date -u '+%Y-%m-%d %H:%M:%S') UTC"
  for m in "${MAPPINGS[@]}"; do
    IFS='|' read -r name vid serial <<< "$m"
    if [[ -n "$serial" ]]; then
      echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$vid\", ATTRS{serial}==\"$serial\", SYMLINK+=\"$name\""
    else
      echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"$vid\", SYMLINK+=\"$name\""
    fi
  done
} > "$RULES_FILE"

udevadm control --reload-rules
udevadm trigger --subsystem-match=tty
sleep 1

echo "installed $RULES_FILE:"
sed 's/^/  /' "$RULES_FILE"
echo "live aliases:"
for m in "${MAPPINGS[@]}"; do
  name="${m%%|*}"
  if [[ -e "/dev/$name" ]]; then
    printf '  /dev/%s -> %s\n' "$name" "$(readlink -f "/dev/$name")"
  else
    printf '  /dev/%s : NOT PRESENT (device unplugged?)\n' "$name"
  fi
done
